language: ruby

sudo: false
cache: bundler

branches:
  only:
    - master

matrix:
  allow_failures:
    - gemfile: Gemfile
    - gemfile: gemfiles/Gemfile-rspec-3.3.x
    - rvm: ruby-head

rvm:
  - 2.2
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/Gemfile-rspec-3.3.x
  - gemfiles/Gemfile-rspec-3.4.x
  - gemfiles/Gemfile-rspec-3.5.x
